routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserManagementController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\User\AgentCustomerController;
use App\Http\Controllers\User\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});
Route::get('/register', function () {
    return view('auth/register');
});
Route::get('/forget_password', function () {
    return view('auth/forget_password');
});
Route::post('/register', [AuthController::class, 'register']);
Route::post('/email_exist', [AuthController::class, 'emailExist'])->name('emailExist');
Route::get('forget_password', [AuthController::class, 'ForgetPassword'])->name('ForgetPasswordGet');
Route::post('ForgetPasswordPost', [AuthController::class, 'ForgetPasswordStore'])->name('ForgetPasswordPost');
Route::get('reset-password/{token}', [AuthController::class, 'ResetPassword'])->name('ResetPasswordGet');
Route::post('reset-password', [AuthController::class, 'ResetPasswordStore'])->name('ResetPasswordPost');

Route::group(['middleware' => 'auth'], function () {
    //start Admin routes
    Route::group(
        ['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['role:ADMIN']], function () {
        Route::get('/home', [AdminController::class, 'index'])->name('admin.home');
        Route::get('/profile', [AdminController::class, 'profile'])->name('admin.profile');
        Route::post('/updateProfile', [AdminController::class, 'updateProfile'])->name('admin.updateProfile');
        Route::post('/updatePassword', [AdminController::class, 'updatePassword'])->name('admin.updatePassword');

        //User Management
        Route::get('/users', [UserManagementController::class, 'index'])->name('users.index');
        Route::get('users/create',  [UserManagementController::class, 'create'])->name('users.create');
        Route::post('users/store',  [UserManagementController::class, 'store'])->name('users.store');
        Route::post('users/update',  [UserManagementController::class, 'update'])->name('users.update');
        Route::get('users/edit/{id}',  [UserManagementController::class, 'edit'])->name('users.edit');
        Route::get('users/view/{id}',  [UserManagementController::class, 'view'])->name('users.view');
        Route::post('users/delete/{id}',  [UserManagementController::class, 'destroy'])->name('users.destroy');

        //customer info Management
        Route::get('/customer_info', [CustomerController::class, 'index'])->name('customer.index');
        Route::get('/customer_delete/{id}', [CustomerController::class, 'destroy'])->name('customer.destroy');
        Route::get('/customer_view/{id}',  [CustomerController::class, 'show'])->name('customer.show');

        //Package Management
//        Route::get('/packages', [PackageController::class, 'index'])->name('packages.index');
//       Route::get('packages/create',  [PackageController::class, 'create'])->name('packages.create');
//       Route::post('packages/store',  [PackageController::class, 'store'])->name('packages.store');
//       Route::post('packages/update',  [PackageController::class, 'update'])->name('packages.update');
//       Route::get('packages/edit/{id}',  [PackageController::class, 'edit'])->name('packages.edit');
//       Route::get('packages/view/{id}',  [PackageController::class, 'view'])->name('packages.view');
//       Route::post('packages/delete/{id}',  [PackageController::class, 'destroy'])->name('packages.destroy');

    });

    //start Users routes
    Route::group(
        ['namespace' => 'User', 'prefix' => 'user', 'as' => 'user.', 'middleware' => ['role:AGENT']], function () {
        Route::get('/home', [UserController::class, 'index'])->name('user.home');
        Route::get('/profile', [UserController::class, 'profile'])->name('user.profile');
        Route::post('/updateProfile', [UserController::class, 'updateProfile'])->name('user.updateProfile');
        Route::post('/updatePassword', [UserController::class, 'updatePassword'])->name('user.updatePassword');

        //customer info Management
        Route::get('/customer_info', [AgentCustomerController::class, 'index'])->name('customer.index');
        Route::get('/customer_delete/{id}', [AgentCustomerController::class, 'destroy'])->name('customer.destroy');
        Route::get('/customer_view/{id}',  [AgentCustomerController::class, 'show'])->name('customer.show');
    });
});


Route::get('/logout', [AuthController::class, 'logout']);
Route::post('/login', [AuthController::class, 'login']);
Route::get('/login', function () {
    return view('auth/login');
});
\URL::forceScheme('https');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role',
        'avatar',
        'name',
        'email',
        'password',
        'mobile',
        'status',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()

    {
        return $this
            ->belongsToMany('App\Models\Role')
            ->withTimestamps();
    }
    public function authorizeRoles($roles)

    {
        if ($this->hasAnyRole($roles)) {
            return true;
        }
        abort(401, 'This action is unauthorized.');
    }
    public function hasAnyRole($roles)
    {
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
        } else {
            if ($this->hasRole($roles)) {
                return true;
            }
        }
        return false;
    }
    public function hasRole($role)
    {
        if ($this->roles()->where('name', $role)->first()) {
            return true;
        }
        return false;
    }

}

app/Http/Controllers/User/AgentCustomerController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\RoleUser;
use App\Models\Customers;
use App\Models\Block;
use Carbon\Carbon;
use Yajra\DataTables\Facades\DataTables;

class AgentCustomerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:AGENT');
    }
    public function index(Request $request)
    {
        // dd($data->user->name);
        $user = $request->user();
        if ($request->ajax()) {

            $data = Customers::with('block')->where('status','0')->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->editColumn('created_at', function ($request) {
                    return Carbon::parse($request->created_at)->toDateString();
                })
                ->editColumn('block_id', function ($request) {
                    return $request->block->name;
                })
                ->addColumn('action', function($row){
                    $button ='<a href="'. route('user.customer.show',$row->id).'"> <i class="fas fa-eye"></i></a>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('user.customers.customer_info',compact('user'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Request $request,$id)
    {
        $data = Customers::with('block')->where('id',$id)->first();
        $user = $request->user();
        return view('user.customers.customer_view',compact('data','user'));
    }

    public function edit(Request $request,$id)
    {
      //
    }

    public function update(Request $request)
    {
       //
    }

    public function destroy($id)
    {
        // dd($id);
        $delete = Customers::where('id',$id)->update(['status' => 1]);
        return response()->json(['success' => true]);
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Customers;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:AGENT');
    }
    //
    public function index(Request $request)
    {
        $user = $request->user();
        $agent = User::where('role','AGENT')->get();
        $customer = Customers::where('status',0)->get();
//        dd($customer);
        return view('user.home',compact('user','customer','agent'));
    }
    public function profile(Request $request)
    {
        $user = $request->user();
        return view('user.profile',compact('user'));
    }
    public function updateProfile(Request $request)
    {
//        dd('222');
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required | email',
            'avatar' => 'image|mimes:jpg,jpeg,png,gif'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error', $validator->messages()->first());
        }
        $user = $request->user();
        if (isset($request->email)) {
            $check = User::where('email', $request->email)
                ->where('id', '!=', $user->id)
                ->first();

            if ($check) {
                return response([
                    'message' => 'The email address is already used!',
                    'success' => 0,
                ]);
            }
        }
        $fileName = null;
        if (request()->hasFile('avatar')) {
            $file = request()->file('avatar');
            $fileName = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
            $file->move('./uploads/', $fileName);
        }
        $data = [
            'id' => $request->id,
            'name' => $request->name,
            'email' => $request->email,
            'avatar' => $fileName,
        ];
//        dd($data);
        $user = User::find($request->id);
        $user = $user->update($data);

        return redirect('/user/profile')->with('success', 'Profile Updated Successfully');
    }
    public function updatePassword(Request $request)
    {
//        dd($request->all());
        $validator = Validator::make($request->all(), [
            'password' => 'required_with:confirm_password|same:confirm_password|min:6',
        ]);

        if ($validator->fails()) {
            dd($validator->messages()->first());
            return redirect()->back()->withInput()->with('error', $validator->messages()->first());
        }

        $data = [
            'id' => $request->id,
            'password' => Hash::make($request->password),
            'confirm_password' => Hash::make($request->confirm_password),
        ];
//        dd($data);
        $user = User::find($request->id);
        $user = $user->update($data);
        return redirect('/user/profile')->with('success', 'Password Updated Successfully');
    }
}

resources/views/admin/users/create.blade.php
@extends('includes.nav')
@include('includes.header')
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Monderia</title>
    <!-- core:css -->
    <link rel="stylesheet" href="../../../assets/vendors/core/core.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="../../../assets/vendors/select2/select2.min.css">
    <link rel="stylesheet" href="../../../assets/vendors/jquery-tags-input/jquery.tagsinput.min.css">
    <link rel="stylesheet" href="../../../assets/vendors/dropzone/dropzone.min.css">
    <link rel="stylesheet" href="../../../assets/vendors/dropify/dist/dropify.min.css">
    <link rel="stylesheet" href="../../../assets/vendors/bootstrap-colorpicker/bootstrap-colorpicker.min.css">
    <link rel="stylesheet" href="../../../assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="../../../assets/vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../../assets/vendors/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css">
    <!-- end plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="../../../assets/fonts/feather-font/css/iconfont.css">
    <link rel="stylesheet" href="../../../assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../../assets/css/demo_1/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="../../../assets/images/favicon.png" />
</head>
<body>
<div class="main-wrapper">

    <!-- partial:../../partials/_sidebar.html -->
    <nav class="settings-sidebar">
        <div class="sidebar-body">
            <a href="#" class="settings-sidebar-toggler">
                <i data-feather="settings"></i>
            </a>
            <h6 class="text-muted">Sidebar:</h6>
            <div class="form-group border-bottom">
                <div class="form-check form-check-inline">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="sidebarThemeSettings" id="sidebarLight" value="sidebar-light" checked>
                        Light
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="sidebarThemeSettings" id="sidebarDark" value="sidebar-dark">
                        Dark
                    </label>
                </div>
            </div>
            <div class="theme-wrapper">
                <h6 class="text-muted mb-2">Light Theme:</h6>
                <a class="theme-item active" href="../../../demo_1/dashboard-one.html">
                    <img src="../../../assets/images/screenshots/light.jpg" alt="light theme">
                </a>
                <h6 class="text-muted mb-2">Dark Theme:</h6>
                <a class="theme-item" href="../../../demo_2/dashboard-one.html">
                    <img src="../../../assets/images/screenshots/dark.jpg" alt="light theme">
                </a>
            </div>
        </div>
    </nav>
    <!-- partial -->

    <div class="page-wrapper">

        <!-- partial:../../partials/_navbar.html -->

        <!-- partial -->

        <div class="page-content">

            <nav class="page-breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?php echo URL::to('/admin/users'); ?>">Users</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Add User</li>
                </ol>
            </nav>
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        @if (\Session::has('success'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('success') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <i class="ik ik-x"></i>
                                </button>
                            </div>
                        @elseif(\Session::has('error'))
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ session('error') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <i class="ik ik-x"></i>
                                </button>
                            </div>
                        @endif
                        <div class="card-body">
                            <h4 class="card-title">Add User</h4>
                            <form id="signupForm" method="post" action=" {{ route('admin.users.store') }} ">
                                @csrf
                                 <div class="row">
                                     <div class="form-group col-md-4">
                                         <label>Role</label>
                                         <select class="js-example-basic-single w-100" name="role">
                                             <option value="" disabled>Select Role</option>
{{--                                             <option value="ADMIN">ADMIN</option>--}}
                                             <option value="AGENT">AGENT</option>
                                         </select>
                                     </div>
                                    <div class="form-group col-md-4">
                                        <label for="name">Name</label>
                                        <input id="name" class="form-control" name="name" type="text">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="email">Email</label>
                                        <input id="email" class="form-control" name="email" type="email">
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="form-group col-md-4">
                                        <label for="password">Password</label>
                                        <input id="password" class="form-control" name="password" type="password">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="confirm_password">Confirm password</label>
                                        <input id="confirm_password" class="form-control" name="confirm_password" type="password">
                                    </div>
                                </div>
                                <button class="btn btn-primary" type="submit" name="submit" >Submit</button>
                                <a class="btn btn-danger" href="<?php echo URL::to('/admin/users'); ?>" >Cancel</a>

                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>

        <!-- partial:../../partials/_footer.html -->
        <footer class="footer d-flex flex-column flex-md-row align-items-center justify-content-between">
            <p class="text-muted text-center text-md-left">Copyright © 2022 <a href="https://monderia.iqlanceserver.com/"
                                                                               target="_blank">Monderia</a>. All rights
                reserved</p>
            {{--            <p class="text-muted text-center text-md-left mb-0 d-none d-md-block">Handcrafted With <i--}}
            {{--                    class="mb-1 text-primary ml-1 icon-small" data-feather="heart"></i></p>--}}
        </footer>
        <!-- partial -->

    </div>
</div>


<!-- core:js -->
<script src="../../../assets/vendors/core/core.js"></script>
<!-- endinject -->
<!-- plugin js for this page -->
<script src="../../../assets/vendors/jquery-validation/jquery.validate.min.js"></script>
<script src="../../../assets/vendors/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<script src="../../../assets/vendors/inputmask/jquery.inputmask.min.js"></script>
<script src="../../../assets/vendors/select2/select2.min.js"></script>
<script src="../../../assets/vendors/typeahead.js/typeahead.bundle.min.js"></script>
<script src="../../../assets/vendors/jquery-tags-input/jquery.tagsinput.min.js"></script>
<script src="../../../assets/vendors/dropzone/dropzone.min.js"></script>
<script src="../../../assets/vendors/dropify/dist/dropify.min.js"></script>
<script src="../../../assets/vendors/bootstrap-colorpicker/bootstrap-colorpicker.min.js"></script>
<script src="../../../assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="../../../assets/vendors/moment/moment.min.js"></script>
<script src="../../../assets/vendors/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.js"></script>
<!-- end plugin js for this page -->
<!-- inject:js -->
<script src="../../../assets/vendors/feather-icons/feather.min.js"></script>
<script src="../../../assets/js/template.js"></script>
<!-- endinject -->
<!-- custom js for this page -->
<script src="../../../assets/js/form-validation.js"></script>
<script src="../../../assets/js/bootstrap-maxlength.js"></script>
<script src="../../../assets/js/inputmask.js"></script>
<script src="../../../assets/js/select2.js"></script>
<script src="../../../assets/js/typeahead.js"></script>
<script src="../../../assets/js/tags-input.js"></script>
<script src="../../../assets/js/dropzone.js"></script>
<script src="../../../assets/js/dropify.js"></script>
<script src="../../../assets/js/bootstrap-colorpicker.js"></script>
<script src="../../../assets/js/datepicker.js"></script>
<script src="../../../assets/js/timepicker.js"></script>
<!-- end custom js for this page -->
</body>
</html>